---
- name: Create RHEL Activation Key for Development guests
  command: hammer activation-key create --organization "{{satellite_organization}}" --description 'Activation Key for guests in Development Environment for RHEL 7 servers' --content-view 'Development-RHEL7' --unlimited-hosts --name ak-Reg_To_Development-rhel7 --lifecycle-environment 'Development'
  tags: activation-key

- name: register subscription-id variable for RHEL Server Premium
  shell: hammer --output='csv' subscription list --organization RedHat --search='Red Hat Enterprise Linux Server, Premium'| tail -n+2 | cut -d ',' -f 1
  register: rhel_server_premium_subid
  tags: activation-key

- name: register subscription-id variable for EPEL
  shell: hammer --output='csv' subscription list --organization RedHat --search='Extra Packages for Enterprise Linux'| tail -n+2 | cut -d ',' -f 1
  register: epel_subid
  tags: activation-key

- name: Attach subscriptions to Activation Key for Development
  command: hammer activation-key add-subscription --name ak-Reg_To_Development-rhel7 --subscription-id {{ item }} --organization "{{satellite_organization}}"
  with_items:
    - "{{rhel_server_premium_subid.stdout}}"
    - "{{epel_subid.stdout}}"
  tags: activation-key

- name: Enable Sat Tools 6.4 channel in Development Activation Key
  command: hammer activation-key content-override --name ak-Reg_To_Development-rhel7 --organization "{{satellite_organization}}" --content-label rhel-7-server-satellite-tools-6.4-rpms --value 1
  tags: activation-key

- name: Create RHEL Activation Key for Lab guests
  command: hammer activation-key create --organization "{{satellite_organization}}" --description 'Activation Key for guests in Lab Environment for RHEL 7 servers' --content-view 'Lab-RHEL7-EAP7' --unlimited-hosts --name ak-Reg_To_Lab-rhel7 --lifecycle-environment 'Lab'
  tags: activation-key

- name: Attach subscriptions to Activation Key for Lab
  command: hammer activation-key add-subscription --name ak-Reg_To_Lab-rhel7 --subscription-id {{ rhel_server_premium_subid.stdout }} --organization "{{satellite_organization}}"
  tags: activation-key

- name: Enable Sat Tools 6.3 channel in Lab Activation Key
  command: hammer activation-key content-override --name ak-Reg_To_Lab-rhel7 --organization "{{satellite_organization}}" --content-label rhel-7-server-satellite-tools-6.4-rpms --value 1
  tags: activation-key
