---
- name: Load OpenSCAP content
  command: foreman-rake foreman_openscap:bulk_upload:default
  tags: openscap

- name: Download Standard Policy Tailoring file from Laptop
  get_url:
    url: http://{{ laptop_ip }}/ssg-rhel7-ds-tailoring-standard-rnelson.xml
    dest: /root/ssg-rhel7-ds-tailoring-standard-rnelson.xml
    mode: 0644
    backup: yes
    force: yes
  tags: openscap

## https://github.com/Ansible-Security-Compliance
