---
- hosts: rhhi
  name: Prepare systems before installing RHHI
  roles:
    - etc-hosts
    - ssh-keys
    - known-hosts
    - register
# the role below is only needed for custom disk layouts. Update roles/disk-prep/tasks/main.yml file with customizations
#    - disk-prep

- hosts: "{{ node1_fqdn }}"
  name: Configure Gluster and Deploy Hosted Engine
  roles:
    - configure-gluster
    - deploy-hosted-engine

- hosts: localhost
  gather_facts: no
  roles:
    - add-hosts
    - add-gluster-network
    - add-storage-domains
