#ansible-playbook -u root main.yml -k
---
- hosts: rhhi
  name: Prepare systems before installing RHHI
  roles:
    - etc-hosts
    - ssh-keys
    - known-hosts
    - register

- hosts: rhhi1.rnelson-demo.com
  name: Configure Gluster and Deploy Hosted Engine
  roles:
    - configure-gluster
    - deploy-hosted-engine

- hosts: localhost
  gather_facts: no
  roles:
    - add-hosts
    - add-gluster-network
    - add-storage-domains
