---
# On control node: ansible-galaxy install ovirt.image-template
# download copy of kvm image and upload to synology
# ansible-playbook 3-ovirt-image-template.yml -e @group_vars/all
- name: oVirt image template
  hosts: localhost
  connection: local
  gather_facts: false


  vars:
    engine_url: https://rhvm.rnelson-demo.com/ovirt-engine/api
    engine_user: admin@internal
    engine_password: RedHat1!
    engine_insecure: true
#    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    qcow_url: ftp://{{qcow_url_ip}}/PXE/isos/rhel-7-kvm-image.qcow2
    template_cluster: Default
    template_name: rhel-7.6-kvm
    template_memory: 2GiB
    template_cpu: 2
    template_disk_size: 10GiB
    template_disk_storage: hosted_storage
    template_type: server


  roles:
    - ovirt.image-template
