---
- hosts: gluster
  name: Initial Setup for Gluster Nodes

  tasks:
    - name: Register to RHN and attach SKU through Activation Key
      redhat_subscription:
        state: present
        activationkey: "{{ activation_key }}"
        org_id: "{{ rhn_org_id }}"

    - name: Disable All Repositories
      command: subscription-manager repos --disable "*"

    - name: Enable Repositories
      command: /usr/sbin/subscription-manager repos --enable="{{item}}"
      with_items: "{{ repos }}"

    - name: Install RPMs
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - redhat-storage-server
        - gstatus
        - ansible
        - gdeploy

    - name: Update
      yum:
        name: "*"
        state: latest

    - name: Start and Enable firewalld
      systemd: name=firewalld state=started enabled=yes

    - name: Configure firewalld
      firewalld:
        service: glusterfs
        permanent: true
        immediate: yes
        state: enabled

    - name: Reboot
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0
