---
- name: Configure OS
  hosts: all
  become: yes
  roles:
    - hostname
    - firewall
    - register
    - ssh-keys

- name: Install and Configure Satellite
  hosts: all
  become: yes
  roles:
    - install-satellite-idm-integrated
    - configure-satellite-idm-integrated
    - manifest
    - domain
    - openscap
    - sync-plan
    - lazy-sync
    - lifecycle-environments
    - product-repo-RHEL7
    - product-repo-EPEL7
    - ccv-RHEL7-EPEL7
    - product-repo-EAP7
    - ccv-RHEL7-EAP7
    - activation-keys
    - provision-libvirt
    - reboot
