---
#the template has already been created. It uses local host storage for OS disk.
# This playbook is to be run on the bastion server
#ansible-playbook -u root 1-ovirt-vm-infra-deploy.yml -k
- name: oVirt VM infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ovirt-vm-infra-vars.yml

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://rhvm.rnelson-demo.com/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: RedHat1!

    - name: Create Master VMs
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        template: rhel-7.6-kvm-ssh
        storage_domain: ssdvmstore
        name: "{{ item }}"
        state: running
        instance_type: Medium
        high_availability: yes
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        cloud_init:
          host_name: "{{ item }}.rnelson-demo.com"
          user_name: root
          root_password: RedHat1!
          authorized_ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmn8iPMGUA5Pf+5Rl+APPs0IGdFlmbSm04/bn2LXBIE3kF4tH/MvZdcJCQEKegC/bSicqEPz8BYFkNPNqqY52bVwIbneHIPraJDD8HhGiIY/A32mGjLr4rZ+FBo14Hy/rkq8WdmxbrrSX61zHEwHEC369jH43RzvICjdlAzHwO2+cnkteKCcRkAFrcSlgyrr0tt9HTUMVB7FPBFrqplxZGLuGlxdRSOA9vAupaJ44VBPtUA7hEaUyK9DQBWIKoBjdM/S/n8ySq3zCGeh6oeSXwD605VPDRSre5NWwvtO86eBOdT00WHtGhvalij4UX2s3zYN8DyRqxS3VHjKku0gCZ rnelson@laptop.rnelson-demo.com
          nic_name: eth0
          nic_on_boot: true
          nic_boot_protocol: dhcp

          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ item }}.rnelson-demo.com
#              - yum -y remove cloud-init
        wait: true
      with_items:
         - ocp-master1
         - ocp-master2
         - ocp-master3

    - name: Create and attach disks for Masters
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ item.vm_name }}"
        storage_domain: "ssdvmstore"
        name: "{{ item.name }}-{{ item.id }}"
        size: "{{ item.size }}"
        format: cow
        interface: virtio
        wait: true
      with_items:
        - { vm_name: 'ocp-master1', name: 'docker_disk', id: '1', size: '70GiB' }
#        - { vm_name: 'ocp-master1', name: 'etcd_disk', id: '2', size: '25GiB' }
        - { vm_name: 'ocp-master2', name: 'docker_disk', id: '1', size: '70GiB' }
#        - { vm_name: 'ocp-master2', name: 'etcd_disk', id: '2', size: '25GiB' }
        - { vm_name: 'ocp-master3', name: 'docker_disk', id: '1', size: '70GiB' }
#        - { vm_name: 'ocp-master3', name: 'etcd_disk', id: '2', size: '25GiB' }

    - name: Create Infra and App VMs
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        template: rhel-7.6-kvm-ssh
        storage_domain: ssdvmstore
        name: "{{ item }}"
        state: running
        instance_type: Medium
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        cloud_init:
          host_name: "{{ item }}.rnelson-demo.com"
          user_name: root
          root_password: RedHat1!
          authorized_ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmn8iPMGUA5Pf+5Rl+APPs0IGdFlmbSm04/bn2LXBIE3kF4tH/MvZdcJCQEKegC/bSicqEPz8BYFkNPNqqY52bVwIbneHIPraJDD8HhGiIY/A32mGjLr4rZ+FBo14Hy/rkq8WdmxbrrSX61zHEwHEC369jH43RzvICjdlAzHwO2+cnkteKCcRkAFrcSlgyrr0tt9HTUMVB7FPBFrqplxZGLuGlxdRSOA9vAupaJ44VBPtUA7hEaUyK9DQBWIKoBjdM/S/n8ySq3zCGeh6oeSXwD605VPDRSre5NWwvtO86eBOdT00WHtGhvalij4UX2s3zYN8DyRqxS3VHjKku0gCZ rnelson@laptop.rnelson-demo.com
          nic_name: eth0
          nic_on_boot: true
          nic_boot_protocol: dhcp

          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ item }}.rnelson-demo.com
#              - yum -y remove cloud-init
        wait: true
      with_items:
         - ocp-infra1
         - ocp-infra2
         - ocp-infra3
         - ocp-app1
         - ocp-app2
         - ocp-app3

    - name: Create and attach disks for Infra nodes
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ item.vm_name }}"
        storage_domain: "ssdvmstore"
        name: "{{ item.name }}-{{ item.id }}"
        size: "{{ item.size }}"
        format: cow
        interface: virtio
        wait: true
      with_items:
        - { vm_name: 'ocp-infra1', name: 'docker_disk', id: '1', size: '70GiB' }
        - { vm_name: 'ocp-infra2', name: 'docker_disk', id: '1', size: '70GiB' }
        - { vm_name: 'ocp-infra3', name: 'docker_disk', id: '1', size: '70GiB' }

    - name: Create and attach disks for App nodes
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ item.vm_name }}"
        storage_domain: "nvmevmstore"
        name: "{{ item.name }}-{{ item.id }}"
        size: "{{ item.size }}"
        format: cow
        interface: virtio
        wait: true
      with_items:
        - { vm_name: 'ocp-app1', name: 'docker_disk', id: '1', size: '70GiB' }
        - { vm_name: 'ocp-app2', name: 'docker_disk', id: '1', size: '70GiB' }
        - { vm_name: 'ocp-app3', name: 'docker_disk', id: '1', size: '70GiB' }

    - name: Create Load Balancer VM
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        template: rhel-7.6-kvm-ssh
        storage_domain: ssdvmstore
        name: "{{ item }}"
        state: running
        instance_type: Small
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        cloud_init:
          host_name: "{{ item }}.rnelson-demo.com"
          user_name: root
          root_password: RedHat1!
          authorized_ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmn8iPMGUA5Pf+5Rl+APPs0IGdFlmbSm04/bn2LXBIE3kF4tH/MvZdcJCQEKegC/bSicqEPz8BYFkNPNqqY52bVwIbneHIPraJDD8HhGiIY/A32mGjLr4rZ+FBo14Hy/rkq8WdmxbrrSX61zHEwHEC369jH43RzvICjdlAzHwO2+cnkteKCcRkAFrcSlgyrr0tt9HTUMVB7FPBFrqplxZGLuGlxdRSOA9vAupaJ44VBPtUA7hEaUyK9DQBWIKoBjdM/S/n8ySq3zCGeh6oeSXwD605VPDRSre5NWwvtO86eBOdT00WHtGhvalij4UX2s3zYN8DyRqxS3VHjKku0gCZ rnelson@laptop.rnelson-demo.com
          nic_name: eth0
          nic_on_boot: true
          nic_boot_protocol: dhcp

          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ item }}.rnelson-demo.com
#              - yum -y remove cloud-init
        wait: true
      with_items:
         - ocp-lb

    - name: Create RHHI-1 Affinity Group
      ovirt_affinity_group:
        auth: "{{ ovirt_auth }}"
        name: rhhi-1-ag
        cluster: "{{ rhv_cluster }}"
        vm_enforcing: true
        vm_rule: positive
        host_enforcing: true
        host_rule: positive
        vms:
          - ocp-master1
          - ocp-infra1
          - ocp-app1
        hosts:
          - rhhi1.rnelson-demo.com
        wait: yes

    - name: Create RHHI-2 Affinity Group
      ovirt_affinity_group:
        auth: "{{ ovirt_auth }}"
        name: rhhi-2-ag
        cluster: "{{ rhv_cluster }}"
        vm_enforcing: true
        vm_rule: positive
        host_enforcing: true
        host_rule: positive
        vms:
          - ocp-master2
          - ocp-infra2
          - ocp-app2
        hosts:
          - rhhi2.rnelson-demo.com
        wait: yes

    - name: Create RHHI-3 Affinity Group
      ovirt_affinity_group:
        auth: "{{ ovirt_auth }}"
        name: rhhi-3-ag
        cluster: "{{ rhv_cluster }}"
        vm_enforcing: true
        vm_rule: positive
        host_enforcing: true
        host_rule: positive
        vms:
          - ocp-master3
          - ocp-infra3
          - ocp-app3
        hosts:
          - rhhi3.rnelson-demo.com
        wait: yes

    - name: Stop VMs to force rebalance/pinning to host, rhevm module missing
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: "{{ item }}"
        state: stopped
      with_items:
        - ocp-master1
        - ocp-master2
        - ocp-master3
        - ocp-infra1
        - ocp-infra2
        - ocp-infra3
        - ocp-app1
        - ocp-app2
        - ocp-app3

    - name: Start VMs to force rebalance/pinning to host, rhevm module missing
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: "{{ item }}"
        state: running
      with_items:
        - ocp-master1
        - ocp-master2
        - ocp-master3
        - ocp-infra1
        - ocp-infra2
        - ocp-infra3
        - ocp-app1
        - ocp-app2
        - ocp-app3

    - name: sleep for 300 seconds and continue with play
      wait_for: timeout=300
      delegate_to: localhost

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

- hosts: localhost
  name: add ocp hosts to known_hosts

  tasks:
    - name: ensure SSH key is generated
      command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
      args:
        creates: /root/.ssh/id_rsa

    - name: Create known_hosts
      shell: "ssh-keyscan -t ecdsa-sha2-nistp256 {{item}} >> /root/.ssh/known_hosts"
      with_items:
        - ocp-master1
        - ocp-master2
        - ocp-master3
        - ocp-infra1
        - ocp-infra2
        - ocp-infra3
        - ocp-app1
        - ocp-app2
        - ocp-app3
        - ocp-lb

- hosts: ocp
  name: Prepare nodes prior to OCP 3.11 Install
  gather_facts: yes
  vars:
    idm_register_username: admin
    idm_register_password: RedHat1!
    repos:
    repo_list:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.11-rpms
      - rhel-7-server-ansible-2.7-rpms
#      - rh-gluster-3-client-for-rhel-7-server-rpms

  tasks:
  - name: Install Bastion's root SSH public key
    authorized_key:
      user: root
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    tags: keys

  - name: Install SSH public key
    authorized_key:
      user: root
      key: "{{ lookup('file', 'rnelson-homelab.pub') }}"
    tags: keys

  - name: Register
    command: subscription-manager register --activationkey={{activation_key}} --org={{rhn_org_id}}
    ignore_errors: yes #Added this because I'm using the Employee SKU, and the auto attach may fail
    tags: register

  - name: Disable All and Enable Specific Repositories
    block:
    - set_fact:
        repos: "{{ repo_list | join(' --enable=') }}"
    - debug:
        var: repos
    - name: Enable repos for RHEL7
      command: subscription-manager repos --disable="*" --enable={{ repos }}
    tags: register

  - name: Install misc packages
    package:
      name: wget,git,net-tools,bind-utils,yum-utils,iptables-services,bridge-utils,bash-completion,kexec-tools,sos,psacct,openshift-ansible,docker-1.13.1,ipa-client,glusterfs-fuse
      state: present
    tags: rpms

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Reboot
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: Wait for the reboot to complete
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300

  - name: "Setup docker-storage-setup"
    copy:
      content: |
        STORAGE_DRIVER=devicemapper
        DEVS=/dev/vdb
        VG=docker-vg
        CONTAINER_THINPOOL=docker_pool
      dest: /etc/sysconfig/docker-storage-setup

  - name: "Run docker-storage-setup"
    command: docker-storage-setup

  - name: "Start and enable docker"
    systemd:
      unit: docker.service
      state: restarted
      enabled: yes

#  - name: Enroll with IdM Server
#    command: ipa-client-install -U --mkhomedir -p {{idm_register_username}} -w {{idm_register_password}}
